FROM ubuntu

RUN apt update
RUN apt upgrade -y
RUN apt install wget -y
RUN apt install npm -y
RUN apt install tmux -y
RUN apt install curl -y

SHELL ["/bin/bash", "-c"]

# Now any RUN command will use Bash
RUN echo "Switched to Bash"


RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
RUN source ~/.nvm/nvm.sh


RUN mkdir /usr/src/destra-storage-node
WORKDIR /usr/src/destra-storage-node

COPY .env .
COPY start-destra.sh .

RUN mkdir /tmp/blockstore



#RUN wget https://raw.githubusercontent.com/DestraNetwork/destra-storage-node/main/scripts/destra_storage_ubuntu_setup.sh
COPY destra_storage_ubuntu_setup.sh .
RUN chmod +x destra_storage_ubuntu_setup.sh
RUN ./destra_storage_ubuntu_setup.sh


 
#COPY package*.json ./

#RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev

#COPY . .

#EXPOSE 3000
#CMD [ "node", "server.js" ]

#CMD [ "node", "server.js" ]

#CMD ["sleep", "infinity"]

#ENTRYPOINT tmux new-session -d -s storage-node; tmux send-keys -t storage-node "npm run destra-storage-node" C-m; echo "Destra Storage Node setup completed and running in tmux session 'storage-node'." ; /bin/bash
CMD ["tail", "-f", "/dev/null"]
#CMD ["tail", "-f", "/dev/null"]
